version: '{build}'
image: Visual Studio 2015

configuration:
  - RelWithDebInfo

before_build:
  - mkdir build && cd build
  - cmake ../source/compiler -G "Visual Studio 14 2015" -DCPACK_GENERATOR=ZIP -DCMAKE_GENERATOR_TOOLSET=v100

build_script:
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --config %CONFIGURATION% --target package

test_script:
  - ctest --build-config %CONFIGURATION%

on_failure:
  - type Testing\Temporary\LastTest.log

artifacts:
  - path: build/pawnc-*-windows.zip
    name: Binary package

deploy:
  description: '<Put release description here>'
  provider: GitHub
  auth_token:
    secure: dEyljMC1z2hb032HYJQY+CIZIdQ382cuHU/3LJA96nbqOl5xfGYPVP/TGbJANbtz
  artifact: /pawnc-.*-windows\.zip/
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag: true
